In [19]:
import pandas as pd

In [20]:
data = [
    "omg this movie is lit 🔥🔥",
    "I cant beleive this happend",
    "LOL that was sooo funny 😂",
    "brb going 2 market",
    "gud mrng frnds 😊",
    "This is awsm!!!",
    "idk what u mean",
    "heyyy!!! whats up???",
    "I luv this song ❤️",
    "thnx 4 ur help",
    "pls send d file asap",
    "sooo tired rn 😴",
    "w8 for me",
    "y r u late??",
    "dis is not gud",
    "haha thats gr8 😄",
    "c u soon",
    "omg!!! whattt is this??",
    "im sooo happpy!!!",
    "okkkk done 👍"
]

df = pd.DataFrame(data, columns=["Sentence"])
df

                       Sentence
0      omg this movie is lit 🔥🔥
1   I cant beleive this happend
2     LOL that was sooo funny 😂
3            brb going 2 market
4              gud mrng frnds 😊
5               This is awsm!!!
6               idk what u mean
7          heyyy!!! whats up???
8            I luv this song ❤️
9                thnx 4 ur help
10         pls send d file asap
11              sooo tired rn 😴
12                    w8 for me
13                 y r u late??
14               dis is not gud
15             haha thats gr8 😄
16                     c u soon
17      omg!!! whattt is this??
18            im sooo happpy!!!
19                 okkkk done 👍

In [21]:
def to_lower(text):
    return text.lower()

In [22]:
def remove_punctuation(text):
    punctuations = "!?,.:-;()[]{}'\""
    for p in punctuations:
        text = text.replace(p, "")
    return text

In [28]:
slang_dict = {
    "omg": "oh my god",
    "lol": "laughing out loud",
    "brb": "be right back",
    "idk": "i dont know",
    "u": "you",
    "ur": "your",
    "thnx": "thanks",
    "pls": "please",
    "rn": "right now",
    "gr8": "great",
    "w8": "wait",
    "c": "see",
    "luv": "love",
    "gud": "good",
    "mrng": "morning",
    "frnds": "friends",
    "dis": "this",
    "y": "why",
    "u" : "you"
}

In [29]:
def replace_slang(text):
    words = text.split()
    new_words = []
    
    for word in words:
        if word in slang_dict:
            new_words.append(slang_dict[word])
        else:
            new_words.append(word)
            
    return " ".join(new_words)

In [30]:
df["Processed"] = df["Sentence"].apply(to_lower)
df["Processed"] = df["Processed"].apply(remove_punctuation)
df["Processed"] = df["Processed"].apply(replace_slang)

df

                       Sentence                                Processed
0      omg this movie is lit 🔥🔥           oh my god this movie is lit 🔥🔥
1   I cant beleive this happend              i cant beleive this happend
2     LOL that was sooo funny 😂  laughing out loud that was sooo funny 😂
3            brb going 2 market             be right back going 2 market
4              gud mrng frnds 😊                   good morning friends 😊
5               This is awsm!!!                             this is awsm
6               idk what u mean                i dont know what you mean
7          heyyy!!! whats up???                           heyyy whats up
8            I luv this song ❤️                      i love this song ❤️
9                thnx 4 ur help                       thanks 4 your help
10         pls send d file asap                  please send d file asap
11              sooo tired rn 😴                   sooo tired right now 😴
12                    w8 for me                              wait for me
13                 y r u late??                           why r you late
14               dis is not gud                         this is not good
15             haha thats gr8 😄                       haha thats great 😄
16                     c u soon                             see you soon
17      omg!!! whattt is this??                 oh my god whattt is this
18            im sooo happpy!!!                           im sooo happpy
19                 okkkk done 👍                             okkkk done 👍

In [31]:
df["Processed"] = df["Sentence"].apply(to_lower)
df["Processed"] = df["Processed"].apply(remove_emojis)
df["Processed"] = df["Processed"].apply(normalize_repetition)
df["Processed"] = df["Processed"].apply(remove_punctuation)
df["Processed"] = df["Processed"].apply(replace_slang)
df

                       Sentence                             Processed
0      omg this movie is lit 🔥🔥           oh my god this movie is lit
1   I cant beleive this happend           i cant beleive this happend
2     LOL that was sooo funny 😂  laughing out loud that was soo funny
3            brb going 2 market          be right back going 2 market
4              gud mrng frnds 😊                  good morning friends
5               This is awsm!!!                          this is awsm
6               idk what u mean             i dont know what you mean
7          heyyy!!! whats up???                         heyy whats up
8            I luv this song ❤️                      i love this song
9                thnx 4 ur help                    thanks 4 your help
10         pls send d file asap               please send d file asap
11              sooo tired rn 😴                   soo tired right now
12                    w8 for me                           wait for me
13                 y r u late??                        why r you late
14               dis is not gud                      this is not good
15             haha thats gr8 😄                      haha thats great
16                     c u soon                          see you soon
17      omg!!! whattt is this??               oh my god whatt is this
18            im sooo happpy!!!                          im soo happy
19                 okkkk done 👍                              okk done

In [26]:
for i in range(len(df)):
    print("Original :", df["Sentence"][i])
    print("Processed:", df["Processed"][i])
    print("-"*40)

Original : omg this movie is lit 🔥🔥
Processed: oh my god this movie is lit 🔥🔥
----------------------------------------
Original : I cant beleive this happend
Processed: i cant beleive this happend
----------------------------------------
Original : LOL that was sooo funny 😂
Processed: laughing out loud that was sooo funny 😂
----------------------------------------
Original : brb going 2 market
Processed: be right back going 2 market
----------------------------------------
Original : gud mrng frnds 😊
Processed: good morning friends 😊
----------------------------------------
Original : This is awsm!!!
Processed: this is awsm
----------------------------------------
Original : idk what u mean
Processed: i dont know what you mean
----------------------------------------
Original : heyyy!!! whats up???
Processed: heyyy whats up
----------------------------------------
Original : I luv this song ❤️
Processed: i love this song ❤️
----------------------------------------
Original : thnx 4 ur help
Processed: thanks 4 your help
----------------------------------------
Original : pls send d file asap
Processed: please send d file asap
----------------------------------------
Original : sooo tired rn 😴
Processed: sooo tired right now 😴
----------------------------------------
Original : w8 for me
Processed: wait for me
----------------------------------------
Original : y r u late??
Processed: y r you late
----------------------------------------
Original : dis is not gud
Processed: this is not good
----------------------------------------
Original : haha thats gr8 😄
Processed: haha thats great 😄
----------------------------------------
Original : c u soon
Processed: see you soon
----------------------------------------
Original : omg!!! whattt is this??
Processed: oh my god whattt is this
----------------------------------------
Original : im sooo happpy!!!
Processed: im sooo happpy
----------------------------------------
Original : okkkk done 👍
Processed: okkkk done 👍
----------------------------------------